services:
  speedtest-telemetry:
    build: .
    container_name: speedtest-telemetry
    restart: unless-stopped
    privileged: true # Required to run systemd inside the container
    network_mode: host # Allows direct access to host network interfaces
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw # Also required for systemd
      - speedtest-data:/var/lib/speedtest-telemetry

volumes:
  speedtest-data:
